baseURL: "http://example.org/uwe-uwe-example-site"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Uwe Uwe Example Site"
theme: "uwe-uwe"
relativeURLs: true

disableKinds:
    - "section"
    - "taxonomy"
    - "term"
    - "RSS"

params:

    uweuwe:
        metadata:
            author: "Matthias Einbrodt"

        logo: 
            display: true
            src: "/assets/img/uwe-uwe-logo.png"

        shortDesc: 
            display: true
            value: "An example website showcasing the uwe uwe (u²) theme for the static site generator Hugo."

        platformLinks:
            display: true
            displayMode: "as-icons-and-text" # Possible values: as-text | as-icons | as-icons-and-text

            platforms:
                -   name: "github"
                    display: true
                    iconSrc: "/assets/img/icons-platforms/github-icon.svg"
                    target: "https://github.com/mbrt-yeah/uwe-uwe-hugo-example-site"
                    text: "Github"
                    title: "Go to Uwe Uwe (u²) Example Site Github repository"

        toc: 
            display: true

        renderHooks:
            image:
                use: true

            link:
                use: true

            heading:
                use: true

        syntaxHiglighingCustom:
            use: false

markup:
    goldmark:
        renderer:
            unsafe: true

    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: false
        hl_Lines: ""
        lineAnchors: ""
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        noClasses: true
        style: igor
        tabWidth: 4
